# Generated by Django 4.0.4 on 2022-05-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=150)),
                ('title', models.BooleanField(default=1)),
            ],
        ),
    ]
