# Generated by Django 4.0.4 on 2022-05-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatia3', '0002_job_description_job_how_to_apply_alter_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
