# Generated by Django 4.0.4 on 2022-05-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatia3', '0004_alter_job_description_alter_job_title_alter_job_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='how_to_apply',
            field=models.CharField(max_length=100),
        ),
    ]
