# Generated by Django 4.0.4 on 2022-05-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatia3', '0005_alter_job_how_to_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='how_to_apply',
            field=models.TextField(),
        ),
    ]
